version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_TIMEZONE=America/Sao_Paulo
      - APP_KEY=base64:...
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=coodesh-test
      - DB_USERNAME=dev
      - DB_PASSWORD=sandbox
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coodesh-test
      MYSQL_USER: dev
      MYSQL_PASSWORD: sandbox
      MYSQL_ROOT_PASSWORD: sandbox
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
